import { CompanySelector, ModulePageHeader } from '@/components/admin/ModulePageHeader'
import { CalculationLabel, InfoTip } from '@/components/ui/InfoTip'
import { StatusBadge } from '@/components/ui/StatusBadge'
import { formatCurrency } from '@/lib/format'
import { createClient } from '@/utils/supabase/server'

export const dynamic = 'force-dynamic'

type Company = { id: string; razon_social: string; nombre_fantasia: string | null }
type Detail = { id: string; codigo: string; descripcion: string; naturaleza: string; monto: number; orden: number }
type Payslip = { id: string; sueldo_base: number; total_imponible: number; total_tributable: number; total_no_imponible: number; descuentos_legales: number; otros_descuentos: number; aportes_empleador: number; liquido_pagar: number; estado: string; calculo: Record<string, unknown>; trabajador: { rut: string; nombres: string; apellido_paterno: string; apellido_materno: string | null } | Array<{ rut: string; nombres: string; apellido_paterno: string; apellido_materno: string | null }> | null; periodo: { periodo: string; empresa_id: string } | Array<{ periodo: string; empresa_id: string }> | null; detalles: Detail[] }
const one = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] : value

export default async function PayslipsPage({ searchParams }: { searchParams: Promise<{ empresa?: string; periodo?: string }> }) {
  const params = await searchParams
  const supabase = await createClient()
  const { data: companyRows } = await supabase.from('empresas').select('id, razon_social, nombre_fantasia').eq('es_admin', false).order('razon_social')
  const companies = (companyRows ?? []) as Company[]
  const selected = companies.find((item) => item.id === params.empresa) ?? companies[0] ?? null
  const { data: periodRows } = selected ? await supabase.from('periodos_remuneraciones').select('id, periodo').eq('empresa_id', selected.id).order('periodo', { ascending: false }).limit(36) : { data: [] }
  const selectedPeriod = (periodRows ?? []).find((item) => item.periodo.slice(0, 7) === params.periodo) ?? (periodRows ?? [])[0] ?? null
  const { data, error } = selected && selectedPeriod ? await supabase.from('liquidaciones').select('id, sueldo_base, total_imponible, total_tributable, total_no_imponible, descuentos_legales, otros_descuentos, aportes_empleador, liquido_pagar, estado, calculo, trabajador:trabajadores(rut, nombres, apellido_paterno, apellido_materno), periodo:periodos_remuneraciones!inner(periodo, empresa_id), detalles:liquidacion_detalles(id, codigo, descripcion, naturaleza, monto, orden)').eq('periodo.empresa_id', selected.id).eq('periodo_id', selectedPeriod.id).order('created_at', { ascending: false }).limit(500) : { data: [], error: null }
  const payslips = ((data ?? []) as Payslip[]).map((item) => ({ ...item, detalles: [...(item.detalles ?? [])].sort((a, b) => a.orden - b.orden) }))
  const totals = payslips.reduce((acc, item) => ({ taxable: acc.taxable + Number(item.total_imponible || 0), deductions: acc.deductions + Number(item.descuentos_legales || 0) + Number(item.otros_descuentos || 0), employer: acc.employer + Number(item.aportes_empleador || 0), net: acc.net + Number(item.liquido_pagar || 0) }), { taxable: 0, deductions: 0, employer: 0, net: 0 })

  return (
    <div className="mx-auto max-w-[1450px]">
      <ModulePageHeader eyebrow="Remuneraciones · Resultados" title="Liquidaciones" description="Revise resultados por periodo y trabajador. Cada cifra incluye una explicación accesible desde el botón de información." help="Las liquidaciones son resultados parametrizados. Deben revisarse antes de cerrar, publicar, pagar o exportar." actions={<CompanySelector companies={companies} selectedId={selected?.id} />} />
      {selected && <form method="get" className="mt-7 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-end"><input type="hidden" name="empresa" value={selected.id} /><label className="grid flex-1 gap-2 text-sm font-bold text-slate-700">Periodo<select name="periodo" defaultValue={selectedPeriod?.periodo.slice(0, 7) ?? ''} className="h-11 rounded-xl border border-slate-300 bg-white px-3">{(periodRows ?? []).map((period) => <option key={period.id} value={period.periodo.slice(0, 7)}>{period.periodo.slice(0, 7)}</option>)}</select></label><button className="h-11 rounded-xl bg-[#0f2438] px-5 text-sm font-black text-white">Ver periodo</button></form>}
      {error && <div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">No fue posible cargar las liquidaciones.</div>}
      {!selected ? <Empty text="No hay empresas disponibles." /> : !selectedPeriod ? <Empty text="No hay periodos de remuneraciones." /> : <>
        <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total imponible" value={totals.taxable} help="Suma de haberes sujetos a cotizaciones previsionales, limitada por los topes aplicables en cada cálculo." /><Metric label="Descuentos" value={totals.deductions} help="Descuentos legales más otros descuentos registrados. Los aportes del empleador no se incluyen aquí." /><Metric label="Aportes empleador" value={totals.employer} help="Cotizaciones y cargos de cargo del empleador. Se informan como costo adicional y no se descuentan al trabajador." /><Metric label="Líquido a pagar" value={totals.net} help="Haberes imponibles y no imponibles menos descuentos legales y otros descuentos." /></section>

        <section className="mt-7 grid gap-5">{payslips.length === 0 ? <Empty text="No hay liquidaciones calculadas para este periodo." /> : payslips.map((item) => { const worker = one(item.trabajador); return <article key={item.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black text-[#0f2438]">{worker ? `${worker.nombres} ${worker.apellido_paterno} ${worker.apellido_materno ?? ''}`.trim() : 'Trabajador'}</h2><StatusBadge status={item.estado} /></div><p className="mt-1 text-sm text-slate-500">RUT {worker?.rut || '—'} · periodo {selectedPeriod.periodo.slice(0, 7)}</p></div><div className="text-right"><p className="inline-flex items-center text-xs font-black uppercase text-slate-400">Líquido <InfoTip>Resultado final a pagar: haberes totales menos descuentos legales y otros descuentos.</InfoTip></p><p className="text-2xl font-black text-[#134b78]">{formatCurrency(item.liquido_pagar)}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Amount label="Sueldo pagado" value={item.sueldo_base} help="Sueldo base proporcional determinado por contrato y días considerados en el cálculo." /><Amount label="Imponible" value={item.total_imponible} help="Haberes afectos a cotizaciones previsionales." /><Amount label="Tributable" value={item.total_tributable} help="Renta utilizada como base para el Impuesto Único después de las deducciones que correspondan." /><Amount label="No imponible" value={item.total_no_imponible} help="Asignaciones que no integran la base previsional cuando cumplen los requisitos legales." /><Amount label="Descuentos" value={Number(item.descuentos_legales) + Number(item.otros_descuentos)} help="AFP, salud, AFC, impuesto y otros descuentos." /><Amount label="Costo empleador" value={item.aportes_empleador} help="Aportes adicionales de cargo del empleador." /></div><details className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black text-[#134b78]">Ver detalle de conceptos</summary><div className="mt-4 overflow-x-auto"><table className="min-w-[650px] w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs font-black uppercase text-slate-500"><th className="px-3 py-3">Código</th><th className="px-3 py-3">Concepto</th><th className="px-3 py-3">Naturaleza</th><th className="px-3 py-3 text-right">Monto</th></tr></thead><tbody>{item.detalles.map((detail) => <tr key={detail.id} className="border-b border-slate-100"><td className="px-3 py-3 font-bold">{detail.codigo}</td><td className="px-3 py-3">{detail.descripcion}</td><td className="px-3 py-3"><StatusBadge status={detail.naturaleza} /></td><td className="px-3 py-3 text-right font-black">{formatCurrency(detail.monto)}</td></tr>)}</tbody></table></div></details></article> })}</section>
      </>}
    </div>
  )
}

function Metric({ label, value, help }: { label: string; value: number; help: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase text-slate-500"><CalculationLabel label={label} help={help} /></p><InfoTip>{help}</InfoTip></div><p className="mt-3 text-2xl font-black text-[#0f2438]">{formatCurrency(value)}</p></article> }
function Amount({ label, value, help }: { label: string; value: number; help: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="inline-flex items-center text-[11px] font-black uppercase text-slate-400">{label}<InfoTip>{help}</InfoTip></p><p className="mt-1 font-black text-[#17324a]">{formatCurrency(value)}</p></div> }
function Empty({ text }: { text: string }) { return <div className="mt-7 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center font-bold text-slate-500">{text}</div> }
